cacheFileName: "mindsporequestionnaire"
content: "欢迎您参与插件改进计划"
questionnaireUrl: "https://mindspore.cn/news/newschildren?id=1053&highlight=AI%E6%A1%86%E6%9E%B6%E5%8F%91%E5%B1%95%E7%99%BD%E7%9A%AE%E4%B9%A6"
versionCode: "1"